from __future__ import annotations

from typing import Protocol

from ...shared.protocols import EventEnvelope
from .models import NotificationResult, ReplayQueryView, StateSnapshot, WorkflowStateRef


class StateMemoryPort(Protocol):
    def save_workflow(self, command_id: str, workflow: WorkflowStateRef, payload: dict) -> None: ...

    def get_workflow_by_command(self, command_id: str) -> WorkflowStateRef | None: ...

    def get_workflow(self, trace_id: str) -> WorkflowStateRef | None: ...

    def append_event(self, envelope: EventEnvelope) -> None: ...

    def query_events(self, *, trace_id: str | None = None, module: str | None = None, limit: int = 200) -> list[dict]: ...

    def save_strategy(self, strategy_version: str, trace_id: str, payload: dict) -> None: ...

    def latest_strategy(self) -> dict | None: ...

    def save_portfolio(self, trace_id: str, payload: dict) -> None: ...

    def latest_portfolio(self) -> dict | None: ...

    def save_notification_result(self, result: NotificationResult, payload: dict) -> None: ...

    def list_parameters(self) -> list[dict]: ...

    def save_parameter(self, name: str, scope: str, value: dict, *, operator: str, reason: str) -> None: ...

    def capture_snapshot(self, trace_id: str) -> StateSnapshot: ...

    def query_replay(self, *, trace_id: str | None = None, module: str | None = None) -> ReplayQueryView: ...
